spring:
  datasource:
    username: zsq
    password: 19940413
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://111.230.153.94:3306/hellDb?characterEncoding=UTF-8

    initialSize: 2
    minIdle: 2
    maxActive: 20
    maxWait: 60000
    filters: stat
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
#  mvc:
#    static-path-pattern: /**
#  resources:
#    static-locations: classpath:/META-INF/resources/,classpath:/resources/static/
  application:
    name: fastdfs-demo
mybatis:
  configuration:
    mapUnderscoreToCamelCase: true